// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newtonsoft.Json.Linq;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemotePlay.Models.Context;

#nullable disable

namespace RemotePlay.DBTool.Migrations.RemotePlay
{
    [DbContext(typeof(RPContext))]
    partial class RPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemotePlay.Models.DB.Auth.UserDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("t_user_device", (string)null);
                });

            modelBuilder.Entity("RemotePlay.Models.DB.Base.Enum", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EnumCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enum_code");

                    b.Property<string>("EnumKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("enum_key");

                    b.Property<string>("EnumType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("enum_type");

                    b.Property<string>("EnumValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enum_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EnumType");

                    b.HasIndex("SortOrder");

                    b.HasIndex("EnumType", "EnumKey")
                        .IsUnique();

                    b.ToTable("t_base_enum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "streamtype-h264",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "H.264 视频流",
                            EnumCode = "H264",
                            EnumKey = "H264",
                            EnumType = "StreamType",
                            EnumValue = "1",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "streamtype-hevc",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HEVC/H.265 视频流",
                            EnumCode = "HEVC",
                            EnumKey = "HEVC",
                            EnumType = "StreamType",
                            EnumValue = "2",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "streamtype-hevc-hdr",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HEVC/H.265 HDR 视频流",
                            EnumCode = "HEVC_HDR",
                            EnumKey = "HEVC_HDR",
                            EnumType = "StreamType",
                            EnumValue = "3",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "quality-default",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "自动匹配比特率",
                            EnumCode = "DEFAULT",
                            EnumKey = "DEFAULT",
                            EnumType = "Quality",
                            EnumValue = "0",
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "quality-very-low",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "非常低画质（约 2Mbps）",
                            EnumCode = "VERY_LOW",
                            EnumKey = "VERY_LOW",
                            EnumType = "Quality",
                            EnumValue = "2000",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "quality-low",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "低画质（约 4Mbps）",
                            EnumCode = "LOW",
                            EnumKey = "LOW",
                            EnumType = "Quality",
                            EnumValue = "4000",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "quality-medium",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "中等画质（约 6Mbps）",
                            EnumCode = "MEDIUM",
                            EnumKey = "MEDIUM",
                            EnumType = "Quality",
                            EnumValue = "6000",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "quality-high",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "高画质（约 10Mbps）",
                            EnumCode = "HIGH",
                            EnumKey = "HIGH",
                            EnumType = "Quality",
                            EnumValue = "10000",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "quality-very-high",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "非常高画质（约 15Mbps）",
                            EnumCode = "VERY_HIGH",
                            EnumKey = "VERY_HIGH",
                            EnumType = "Quality",
                            EnumValue = "15000",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "fps-low",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "30 帧每秒",
                            EnumCode = "30FPS",
                            EnumKey = "LOW",
                            EnumType = "FPS",
                            EnumValue = "30",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "fps-high",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "60 帧每秒",
                            EnumCode = "60FPS",
                            EnumKey = "HIGH",
                            EnumType = "FPS",
                            EnumValue = "60",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "resolution-360p",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "360p 分辨率预设",
                            EnumCode = "RES_360P",
                            EnumKey = "360p",
                            EnumType = "ResolutionPreset",
                            EnumValue = "{\"width\":640,\"height\":360,\"bitrate\":2000}",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "resolution-540p",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "540p 分辨率预设",
                            EnumCode = "RES_540P",
                            EnumKey = "540p",
                            EnumType = "ResolutionPreset",
                            EnumValue = "{\"width\":960,\"height\":540,\"bitrate\":6000}",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "resolution-720p",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "720p 分辨率预设",
                            EnumCode = "RES_720P",
                            EnumKey = "720p",
                            EnumType = "ResolutionPreset",
                            EnumValue = "{\"width\":1280,\"height\":720,\"bitrate\":10000}",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "resolution-1080p",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1080p 分辨率预设",
                            EnumCode = "RES_1080P",
                            EnumKey = "1080p",
                            EnumType = "ResolutionPreset",
                            EnumValue = "{\"width\":1920,\"height\":1080,\"bitrate\":15000}",
                            IsActive = true,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("RemotePlay.Models.DB.Base.Log", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_id");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<JObject>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("request_path");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.HasIndex("Level", "CreatedAt");

                    b.ToTable("t_base_log", (string)null);
                });

            modelBuilder.Entity("RemotePlay.Models.DB.Base.Settings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_encrypted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<JObject>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("t_settings", (string)null);
                });

            modelBuilder.Entity("RemotePlay.Models.DB.PlayStation.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("APBssid")
                        .HasColumnType("text")
                        .HasColumnName("ap_bssid");

                    b.Property<string>("DiscoverProtocolVersion")
                        .HasColumnType("text")
                        .HasColumnName("discover_protocol_version");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_id");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_name");

                    b.Property<string>("HostType")
                        .HasColumnType("text")
                        .HasColumnName("host_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("IsRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registered");

                    b.Property<DateTime?>("LastPlayDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_play_date");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RPKey")
                        .HasColumnType("text")
                        .HasColumnName("rp_key");

                    b.Property<string>("RPKeyType")
                        .HasColumnType("text")
                        .HasColumnName("rp_key_type");

                    b.Property<JObject>("RegistData")
                        .HasColumnType("jsonb")
                        .HasColumnName("regist_data");

                    b.Property<string>("RegistKey")
                        .HasColumnType("text")
                        .HasColumnName("regist_key");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SystemVersion")
                        .HasColumnType("text")
                        .HasColumnName("system_version");

                    b.Property<Guid>("uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.ToTable("t_playstation_device", (string)null);
                });

            modelBuilder.Entity("RemotePlay.Models.DB.PlayStation.DeviceConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<JObject>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("config_type");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("text")
                        .HasColumnName("config_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId", "DeviceId", "ConfigKey")
                        .IsUnique();

                    b.ToTable("t_device_config", (string)null);
                });

            modelBuilder.Entity("RemotePlay.Models.DB.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("t_user", (string)null);
                });

            modelBuilder.Entity("RemotePlay.Models.DB.Auth.UserDevice", b =>
                {
                    b.HasOne("RemotePlay.Models.DB.PlayStation.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("foreign_k_userdevice_k");

                    b.HasOne("RemotePlay.Models.DB.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemotePlay.Models.DB.PlayStation.DeviceConfig", b =>
                {
                    b.HasOne("RemotePlay.Models.DB.PlayStation.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
